# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79dc6ded24c183853b154a31beea55a3ad4df4205fc20a18f84a8c8c9274b8649e720598150f300cef39df5c9179cfda6fc670a10a929af9bdd0aff343fca94e
  aws_access_key_id: AKIAJENJWQJKBOWF4WNQ
  aws_secret_access_key: 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

test:
  secret_key_base: fe117e8f92d746d2c67e00ccd69b8d1fe1298b54b4c8eb020c3d611bd5aaa113e9efd282696e2fb6c9bdf7dcc0be66d24b6f21c3ae1962b59ccbb5a614ba80b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: AKIAJENJWQJKBOWF4WNQ
  aws_secret_access_key: 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
